"""
Embedding Provider Interface.

Defines the contract for all embedding models.
"""

from abc import ABC, abstractmethod
from app.domain.entities.embedding_result import EmbeddingResult
from app.domain.exceptions import EmbeddingError


class EmbeddingProvider(ABC):
    """
    Abstract interface for generating vector embeddings.

    All embedding providers (Gemini, OpenAI, Voyage, sentence-transformers, etc.)
    must implement this interface to be swappable.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Return the name of the embedding provider."""
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the dimension of embeddings generated by this provider."""
        pass

    @abstractmethod
    async def generate_embedding(self, text: str) -> EmbeddingResult:
        """
        Generate embedding for a single text fragment.

        Args:
            text: Input string content.

        Returns:
            EmbeddingResult containing vector and metadata.
        """
        pass

    @abstractmethod
    async def generate_batch_embeddings(self, texts: list[str]) -> EmbeddingResult:
        """
        Generate embeddings for a list of text fragments.

        Args:
            texts: List of strings.

        Returns:
            EmbeddingResult containing list of vectors and metadata.
        """
        pass

    @abstractmethod
    async def health_check(self) -> bool:
        """
        Check if the embedding provider API/service is healthy and reachable.

        Returns:
            True if healthy, False otherwise.
        """
        pass

    # ── Backward Compatibility API ────────────────────────────────
    # Matches the Langchain-like API currently used by RAGChain and ProcessDocumentUseCase.

    async def embed_query(self, text: str) -> list[float]:
        """
        Backward compatible bridge method for embedding search queries.

        Args:
            text: Query string.

        Returns:
            List of floats representing the embedding vector.
        """
        result = await self.generate_embedding(text)
        if not result.success or not result.vector:
            raise EmbeddingError("Query embedding generation failed")
        return result.vector

    async def embed_documents(self, texts: list[str]) -> list[list[float]]:
        """
        Backward compatible bridge method for embedding multiple chunks.

        Args:
            texts: List of chunks.

        Returns:
            List of embedding vectors.
        """
        result = await self.generate_batch_embeddings(texts)
        if not result.success or not result.vectors:
            raise EmbeddingError("Batch embedding generation failed")
        return result.vectors
